# Generated by Django 2.0 on 2018-07-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='auth',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='update_time',
            new_name='last_updated_time',
        ),
    ]
